org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IterableExtensions.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IteratorExtensions.java

(combining existing toMap and toInvertedMap)
Signed-off-by: Artur Biesiadowski <abies@adres.pl>

Added toMap function which allows mapping of both keys and values

---

org.eclipse.xtend.lib/src/org/eclipse/xtend/lib/annotations/EqualsHashCode.xtend
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/EqualsHashCodeProcessor.java

[489237] Generate hashCode in @EqualsHashCode more findbugs-friendly

[489237] Generate hashCode in @EqualsHashCode more findbugs-friendly

---

org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/CollectionExtensionsTest.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/CollectionExtensions.java

[488449] CollectionExtensions operator_add/remove(Collection, Iterable) has wrong signature

[488449] CollectionExtensions operator_add/remove(Collection, Iterable) has wrong signature

---

org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/InputOutput.java

[389147] Add overloaded variants of InputOutput.print and println

[389147] Add overloaded variants of InputOutput.print and println

---

gradle/eclipse-project-layout.gradle
org.eclipse.xtend.lib.gwt.test/build.gradle
org.eclipse.xtend.lib.gwt/build.gradle
org.eclipse.xtend.lib.macro/build.gradle
org.eclipse.xtend.lib.tests/build.gradle
org.eclipse.xtend.lib/build.gradle
org.eclipse.xtext.xbase.lib.gwt/build.gradle
org.eclipse.xtext.xbase.lib.tests/build.gradle
org.eclipse.xtext.xbase.lib/build.gradle

Consistent use of tabs instead of spaces
Use single whitespace between brackets

[format] Streamlined whitespaces

---

org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/IntegerRangeTest.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IntegerRange.java

[381140] Fix IAE for range Integer::MIN_VALUE..0

---

org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/Conversions.java

Signed-off-by: Facundo Etchezar <hctf90@gmail.com>

- Implemented types-specific wrappers for primitive arrays.

---

org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/Conversions.java

- Renamed WrappedIntArray to WrappedIntegerArray for consistency with
Integer class.
- Added an exception to doWrapArray in case of an unrecognised type, to
make the distinction between null argument (returns null) and
unrecognised type (throws exception instead of returning null).
Signed-off-by: Facundo Etchezar <hctf90@gmail.com>

- Added missing wrappers for char[] and boolean[].

---

org.eclipse.xtext.xbase.lib/src/org/eclipse/xtend2/lib/StringConcatenation.java

Revert "Bug 427909: StringConcatenation ca. >30% performance improvement"

---

org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/StringConcatenationTest.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtend2/lib/StringConcatenation.java

This is a set of incremental improvements to StringConcatenation,
which result in ~30% performance increase with Xtend templates.

[427909]: add tests for StringConcatenation and optimize it

---

.gitignore
.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtend.lib.gwt.test/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtend.lib.gwt/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtend.lib.macro/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtend.lib.tests/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtend.lib/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.xbase.lib.gwt/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.xbase.lib.tests/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.xbase.lib/.settings/org.eclipse.buildship.core.prefs

connection.project.dir changed to composite build location in new
umbrella project
value 'containers' added by Buildship

Gradle composite

---

org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/internal/ToStringBuilderTest.xtend
org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/internal/ToStringBuilderTest.java

add test case for ToStringBuilder

---

org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/DataProcessor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/AccessorsProcessor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/DelegateProcessor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/EqualsHashCodeProcessor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/FinalFieldsConstructorProcessor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/ToStringProcessor.java

Changes to generated Xtend code due to compiler optimization

[507077] Do not emit empty concatenation

---

build.gradle
gradle/bootstrap-setup.gradle
gradle/eclipse-project-layout.gradle
gradle/xtend-compiler-settings.gradle

* Use build result from xtend-bootstrap job for Xtend compiler
* Added `skipXtendCompiler` option

Improve Xtend bootstrap

---

gradle/gwtProject.gradle
gradle/gwtSourceProject.gradle
org.eclipse.xtend.lib.gwt.test/build.gradle
org.eclipse.xtend.lib.gwt.test/src/org/eclipse/xtend/lib/test/TestEntryPoint.java
org.eclipse.xtend.lib.gwt/build.gradle
org.eclipse.xtend.lib/build.gradle
org.eclipse.xtext.xbase.lib.gwt/build.gradle
org.eclipse.xtext.xbase.lib/build.gradle

fixed missing gwt sources. #40

---

gradle/gwtProject.gradle
gradle/gwtSourceProject.gradle
org.eclipse.xtend.lib.gwt.test/build.gradle
org.eclipse.xtend.lib.gwt.test/src/org/eclipse/xtend/lib/test/TestEntryPoint.java
org.eclipse.xtend.lib.gwt/build.gradle
org.eclipse.xtend.lib/build.gradle
org.eclipse.xtext.xbase.lib.gwt/build.gradle
org.eclipse.xtext.xbase.lib/build.gradle

fixed missing gwt sources. #40 

---

org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/declaration/MutableAnnotationTypeElementDeclaration.java

added support for creating annotation properties in xtend active annotations
https://github.com/eclipse/xtext-xtend/issues/200

added support for creating annotation properties in xtend active annotations

---

.project
org.eclipse.xtend.lib.gwt.test/.project
org.eclipse.xtend.lib.gwt/.project
org.eclipse.xtend.lib.macro/.project
org.eclipse.xtend.lib.tests/.project
org.eclipse.xtend.lib/.project
org.eclipse.xtext.xbase.lib.gwt/.project
org.eclipse.xtext.xbase.lib.tests/.project
org.eclipse.xtext.xbase.lib/.project

gradleprojectbuilder added by Buildship project import

---

.project
org.eclipse.xtend.lib.gwt.test/.project
org.eclipse.xtend.lib.gwt/.project
org.eclipse.xtend.lib.macro/.project
org.eclipse.xtend.lib.tests/.project
org.eclipse.xtend.lib/.project
org.eclipse.xtext.xbase.lib.gwt/.project
org.eclipse.xtext.xbase.lib.tests/.project
org.eclipse.xtext.xbase.lib/.project

Buildship tooling added automatically org.eclipse.buildship.core.gradleprojectbuilder

gradleprojectbuilder added by Buildship

---

org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/IterableExtensionsTest.java
org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/IteratorExtensionsTest.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IterableExtensions.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IteratorExtensions.java

[#57] Added flatMap

---

org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/declaration/MutableAnnotationTypeElementDeclaration.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/CollectionLiterals.java

Added missing since tags

---

org.eclipse.xtend.lib/META-INF/MANIFEST.MF

[525746] Set lower bound for org.eclipse.xtext.xbase.lib

---

gradle/bootstrap-setup.gradle
gradle/versions.gradle
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtend.gwt/pom.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.gwt/pom.xml
releng/org.eclipse.xtext.license/feature.xml
releng/org.eclipse.xtext.license/pom.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml
releng/org.eclipse.xtext.xbase.lib/pom.xml
releng/p2/category.xml
releng/p2/pom.xml
releng/pom.xml
releng/releng-target/pom.xml

increased versions to 2.14.0

---

org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/declaration/MutableAnnotationTypeElementDeclaration.java
org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/IntegerRangeTest.java
org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/IterableExtensionsTest.java
org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/IteratorExtensionsTest.java
org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/StringConcatenationTest.java
org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/FunctionCompositionTest.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtend2/lib/StringConcatenation.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/CollectionExtensions.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/CollectionLiterals.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/Conversions.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/InputOutput.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IntegerRange.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IterableExtensions.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IteratorExtensions.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/util/ToStringBuilder.xtend
org.eclipse.xtext.xbase.lib/xtend-gen/org/eclipse/xtext/xbase/lib/util/ToStringBuilder.java
org.eclipse.xtext.xbase.lib/xtend-gen/org/eclipse/xtext/xbase/lib/util/ToStringContext.java
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.license/feature.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml

[eclipse/xtext#1160] Update copyright date range

---

org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/FunctionCompositionTest.java
org.eclipse.xtext.xbase.lib/xtend-gen/org/eclipse/xtext/xbase/lib/util/ToStringBuilder.java
org.eclipse.xtext.xbase.lib/xtend-gen/org/eclipse/xtext/xbase/lib/util/ToStringContext.java

[eclipse/xtext#1160] Updated copyright date range

---

org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/util/ReflectExtensionsTest.java

[420984] Compiler optimization: Suppress unused exception variable

---

gradle/p2-deployment.gradle
releng/p2/pom.xml
releng/pom.xml

- Upgrade to Tycho 1.1.0
Regenerated pom.xml with generateP2Build task

[eclipse/xtext#1170] Update p2-deployment.gradle & derived files

---

gradle/java-compiler-settings.gradle
gradle/versions.gradle
org.eclipse.xtend.lib.gwt.test/.classpath
org.eclipse.xtend.lib.gwt.test/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtend.lib.gwt.test/build.gradle
org.eclipse.xtend.lib.gwt/.classpath
org.eclipse.xtend.lib.gwt/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtend.lib.macro/.classpath
org.eclipse.xtend.lib.macro/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtend.lib.tests/.classpath
org.eclipse.xtend.lib.tests/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtend.lib/.classpath
org.eclipse.xtend.lib/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/DataProcessor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/AccessorsProcessor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/DataProcessor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/DelegateProcessor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/EqualsHashCodeProcessor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/FinalFieldsConstructorProcessor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/ToStringProcessor.java
org.eclipse.xtext.xbase.lib.gwt/.classpath
org.eclipse.xtext.xbase.lib.gwt/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.xbase.lib.tests/.classpath
org.eclipse.xtext.xbase.lib.tests/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/FunctionCompositionTest.java
org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/util/ReflectExtensionsTest.java
org.eclipse.xtext.xbase.lib/.classpath
org.eclipse.xtext.xbase.lib/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.xbase.lib/xtend-gen/org/eclipse/xtext/xbase/lib/util/ToStringBuilder.java

 [#51] Update to Java 8

---

org.eclipse.xtend.lib.tests/xtend-gen/org/eclipse/xtend/lib/annotations/DataTest.java
org.eclipse.xtend.lib/src/org/eclipse/xtend/lib/annotations/Data.xtend
org.eclipse.xtend.lib/src/org/eclipse/xtend/lib/annotations/EqualsHashCode.xtend
org.eclipse.xtend.lib/src/org/eclipse/xtend/lib/annotations/ToString.xtend
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/EqualsHashCodeProcessor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/ToStringProcessor.java

Signed-off-by: Titouan Vervack <titouan.vervack@sigasi.com>

Do not create unnecessary vars in toString or hashCode

---

org.eclipse.xtend.lib/src/org/eclipse/xtend/lib/annotations/EqualsHashCode.xtend

Signed-off-by: Titouan Vervack <titouan.vervack@sigasi.com>

Removed redundant modifiers

---

org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/CollectionLiterals.java

Signed-off-by: Titouan Vervack <titouan.vervack@sigasi.com>

Added SafeVarargs

---

gradle/bootstrap-setup.gradle

[eclipse/xtext#1178] bootstrap against 2.14

[eclipse/xtext#1178] bootstrap against 2.14

---

gradle/p2-deployment.gradle
releng/releng-target/xtext-lib.target.target

[eclipse/xtext#1168] set minimal target to oxygen

[eclipse/xtext#1168] set minimal target to oxygen

---

org.eclipse.xtend.lib/.classpath
org.eclipse.xtext.xbase.lib/.classpath

[eclipse/xtext#1247] including attribute added for classpathentry

---

org.eclipse.xtext.xbase.lib.tests/build.gradle
org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/MapExtensionsTest.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/MapExtensions.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/internal/UnmodifiableMergingMapView.java

Signed-off-by: Stéphane Galland <galland@arakhne.org>

Add operators within MapExtensions.

---

org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/MapExtensions.java

[eclipse/xtext-extras#289] Restored MapExtensions.mapValues

[eclipse/xtext-extras#289] Restored MapExtensions.mapValues

---

gradle/versions.gradle
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtend.gwt/pom.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.gwt/pom.xml
releng/org.eclipse.xtext.license/feature.xml
releng/org.eclipse.xtext.license/pom.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml
releng/org.eclipse.xtext.xbase.lib/pom.xml
releng/p2/category.xml
releng/p2/pom.xml
releng/pom.xml
releng/releng-target/pom.xml

updated versions to 2.16.0

---

gradle/versions.gradle
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtend.gwt/pom.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.gwt/pom.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml
releng/org.eclipse.xtext.xbase.lib/pom.xml
releng/p2/category.xml
releng/p2/pom.xml
releng/pom.xml
releng/releng-target/pom.xml

change version 2.16.0 -> 2.17.0

---

releng/p2/pom.xml
releng/pom.xml

[eclipse/xtext#1322] switched to tycho 1.3.0

[eclipse/xtext#1322] switched to tycho 1.3.0

---

releng/org.eclipse.xtext.dev-bom/pom.xml

[eclipse/xtext#1249] Add required metadata for Maven Central

---

2-gradle-build.sh
build.gradle
gradle/developers.gradle
gradle/maven-deployment.gradle
gradle/versions.gradle
releng/org.eclipse.xtext.dev-bom/pom.xml

Revert "[eclipse/xtext#1249] Use Gradle native BOM management"

---

releng/org.eclipse.xtext.dev-bom/pom.xml

added jsr305 version to bom

---

build.gradle

[eclipse/xtext#1387] workaround for oomph problem with bom

[eclipse/xtext#1387] workaround for oomph problem with bom

---

releng/org.eclipse.xtext.dev-bom/pom.xml

[eclipse/xtext#1283] update to MWE 2.10 M2

[eclipse/xtext#1283] update to MWE 2.10 M2

---

org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF

[eclipse/xtext#1391] pin guava version to 21

[eclipse/xtext#1391] pin guava version to 21

---

releng/org.eclipse.xtext.dev-bom/pom.xml
releng/pom.xml

Set sourceEncoding UTF-8

---

org.eclipse.xtend.lib.gwt.test/.classpath
org.eclipse.xtend.lib.gwt/.classpath
org.eclipse.xtend.lib.macro/.classpath
org.eclipse.xtend.lib.tests/.classpath
org.eclipse.xtend.lib/.classpath
org.eclipse.xtext.xbase.lib.gwt/.classpath
org.eclipse.xtext.xbase.lib.tests/.classpath
org.eclipse.xtext.xbase.lib/.classpath

Changes done by Buildship 3.0.1.v20181217-1554

[eclipse/xtext#1274] Updated .classpath by Gradle

---

org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/FunctionExtensions.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IterableExtensions.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IteratorExtensions.java

fixed some javadoc problems with inner classes

---

gradle/versions.gradle
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtend.gwt/pom.xml
releng/org.eclipse.xtext.dev-bom/pom.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.gwt/pom.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml
releng/org.eclipse.xtext.xbase.lib/pom.xml
releng/p2/category.xml
releng/p2/pom.xml
releng/pom.xml
releng/releng-target/pom.xml

[eclipse/xtext#1414] prepared master for vesion 2.18.0

[eclipse/xtext#1414] prepared master for version 2.18.0

---

releng/org.eclipse.xtext.dev-bom/pom.xml

[eclipse/xtext-core#1059] updated lsp4j to version 0.7.0

---

README.md
gradle/bootstrap-setup.gradle

use https to access typefox jenkins

---

CBI.Jenkinsfile
gradle/java-compiler-settings.gradle

Also:
- configure encoding for test execution due to encoding related test
- disable concurrent builds

[eclipse/xtext#1309] Provide Jenkinsfile for Eclipse CBI

---

releng/pom.xml

[eclipse/xtext#1422] update to tycho 1.4.0

[eclipse/xtext#1422] update to tycho 1.4.0

---

releng/org.eclipse.xtext.dev-bom/pom.xml

Signed-off-by: Arne Deutsch <Arne.Deutsch@itemis.de>

[eclipse/xtext#1440] Update to ASM 7.1.0.

---

3-maven-build.sh

[eclipse/xtext#1427] disable p2 mirrors

[eclipse/xtext#1427] disable p2 mirrors

---

gradle/versions.gradle

[eclipse/xtext#1437] Bootstrap against 2.18.0.M2

[eclipse/xtext#1437] Bootstrap against 2.18.0.M2

---

releng/org.eclipse.xtext.dev-bom/pom.xml

[eclipse/xtext-core#1082] update to lsp4j 0.7.1

[eclipse/xtext-core#1082] update to lsp4j 0.7.1

---

org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/declaration/AnnotationReference.java
org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/declaration/ResolvedExecutable.java
org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/declaration/TypeReference.java
org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/services/AnnotationReferenceBuildContext.java
org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/services/TypeReferenceProvider.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/BooleanExtensions.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/ComparableExtensions.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IntegerExtensions.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IntegerRange.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/LongExtensions.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/ObjectExtensions.java

fixed broken/invalid javadoc

---

releng/org.eclipse.xtext.dev-bom/pom.xml

update to lsp4j 0.7.2

---

gradle/versions.gradle
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtend.gwt/pom.xml
releng/org.eclipse.xtext.dev-bom/pom.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.gwt/pom.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml
releng/org.eclipse.xtext.xbase.lib/pom.xml
releng/p2/category.xml
releng/p2/pom.xml
releng/pom.xml
releng/releng-target/pom.xml

Signed-off-by: Nico Prediger <mail@nicoprediger.de>

[eclipse/xtext#1474] Prepare Master for 2.19

---

releng/org.eclipse.xtext.dev-bom/pom.xml

[eclipse/xtext#1485] update to mwe 2.11

---

org.eclipse.xtend.lib.gwt.test/build.gradle

bumped gwt gradle plugin

---

releng/org.eclipse.xtext.dev-bom/pom.xml

bumped platform version to 2019-06

bumped platform version to 2019-06

---

releng/org.eclipse.xtext.dev-bom/pom.xml

splitted variables for versions that are the same by accident

---

org.eclipse.xtend.lib/src/org/eclipse/xtend/lib/annotations/Delegate.xtend
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/DelegateProcessor.java

[#224] Use stable order for generated methods

[#224] Use stable order for generated methods

---

releng/org.eclipse.xtext.dev-bom/pom.xml

manage lsp4j websocket version

manage lsp4j websocket version

---

gradle/versions.gradle
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtend.gwt/pom.xml
releng/org.eclipse.xtext.dev-bom/pom.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.gwt/pom.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml
releng/org.eclipse.xtext.xbase.lib/pom.xml
releng/p2/category.xml
releng/p2/pom.xml
releng/pom.xml
releng/releng-target/pom.xml

[releng] Set version to 2.20.0

---

gradle/wrapper/gradle-wrapper.properties
gradlew
org.eclipse.xtend.lib.gwt.test/.project
org.eclipse.xtend.lib.tests/.classpath
org.eclipse.xtext.xbase.lib.tests/.classpath

[eclipse/xtext#1520] update to gradle 5.6.1

[eclipse/xtext#1520] update to gradle 5.6.1

---

2-gradle-build.sh
build.gradle
gradle/developers.gradle
gradle/maven-deployment.gradle

[eclipse/xtext#1547] use maven-publish instead of maven plugin

[eclipse/xtext#1547] use maven-publish instead of maven plugin

---

releng/releng-target/xtext-lib.target.target

[eclipse/xtext#1538] use orbit 2019-12

[eclipse/xtext#1538] use orbit 2019-12

---

gradle/maven-deployment.gradle

[eclipse/xtext#1547] fixed publication of war

[eclipse/xtext#1547] fixed publication of war

---

releng/pom.xml

[eclipse/xtext#1553] update to tycho 1.5.0

[eclipse/xtext#1553] update to tycho 1.5.0

---

releng/org.eclipse.xtext.dev-bom/pom.xml

[eclipse/xtext#1567] Upgrade to asm 7.2

[eclipse/xtext#1567] Upgrade to asm 7.2

---

releng/pom.xml

[eclipse/xtext#1566] update to tycho 1.5.1

[eclipse/xtext#1566] update to tycho 1.5.1

---

gradle/eclipse-project-layout.gradle
org.eclipse.xtend.lib.gwt/.project
org.eclipse.xtend.lib.macro/.project
org.eclipse.xtend.lib/.project
org.eclipse.xtext.xbase.lib.gwt/.project
org.eclipse.xtext.xbase.lib/.project

[eclipse/xtext#1573] Ensure that all plugins do have a ManifestBuilder

[eclipse/xtext#1573] Ensure that all plugins do have a ManifestBuilder

---

releng/org.eclipse.xtext.dev-bom/pom.xml

[eclipse/xtext#1574] Updated Platform Maven Dependencies to latest version (2019-09)

[eclipse/xtext#1574] Updated Platform Maven Dependencies to latest version (2019-09)

---

org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/IterableExtensionsTest.java
org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/IteratorExtensionsTest.java

fixed unused imports

---

org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/ArrayExtensions.java

removed superflous type parameter

---

org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsObjectTest.java

use latest xbase lib

---

org.eclipse.xtend.lib.gwt.test/src/org/eclipse/xtend/lib/test/Test.gwt.xml

added missing dtd

---

org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/IterableExtensionsTest.java

fixed warnings

---

build.gradle
gradle/manifest-gen.gradle
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF

[eclipse/xtext#1504] added Eclipse-SourceReferences to manifests

[eclipse/xtext#1504] added Eclipse-SourceReferences to manifests

---

org.eclipse.xtend.lib.gwt/build.properties
org.eclipse.xtend.lib.macro/build.properties
org.eclipse.xtend.lib/build.properties
org.eclipse.xtext.xbase.lib.gwt/build.properties
org.eclipse.xtext.xbase.lib/build.properties

[eclipse/xtext#1573] Provide proper build.properties

[eclipse/xtext#1573] Provide proper build.properties

---

releng/org.eclipse.xtext.dev-bom/pom.xml

[eclipse/xtext#1609] update to mwe 2.11.1

[eclipse/xtext#1609] update to mwe 2.11.1

---

releng/org.eclipse.xtext.dev-bom/pom.xml

updated to lsp4j 0.8.1

---

gradle/versions.gradle
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtend.gwt/pom.xml
releng/org.eclipse.xtext.dev-bom/pom.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.gwt/pom.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml
releng/org.eclipse.xtext.xbase.lib/pom.xml
releng/p2/category.xml
releng/p2/pom.xml
releng/pom.xml
releng/releng-target/pom.xml

[releng] Update Xtext version to 2.21.0

---

releng/org.eclipse.xtext.dev-bom/pom.xml

[eclipse/xtext#1638] update to 2019-12 platform maven artifacts

[eclipse/xtext#1638] update to 2019-12 platform maven artifacts

---

releng/org.eclipse.xtext.dev-bom/pom.xml

[eclipse/xtext#1282] update to EMF 2.20

[eclipse/xtext#1282] update to EMF 2.20

---

releng/releng-target/xtext-lib.target.target

[eclipse/xtext#1605] update orbit to 2020-03

[eclipse/xtext#1605] update orbit to 2020-03

---

releng/pom.xml

[eclipse/xtext#1643] update to tycho 1.6.0

[eclipse/xtext#1643] update to tycho 1.6.0

---

org.eclipse.xtext.dev-bom/build.gradle

use lsp 0.9.0-SNAPSHOT

---

org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext-core#1244] update to LSP4J 0.9.0.M3

[eclipse/xtext-core#1244] update to LSP4J 0.9.0.M3

---

gradle/versions.gradle
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtend.gwt/pom.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.gwt/pom.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml
releng/org.eclipse.xtext.xbase.lib/pom.xml
releng/p2/category.xml
releng/p2/pom.xml
releng/pom.xml
releng/releng-target/pom.xml

[releng] Update Xtext version to 2.22.0

---

org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/Data.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/Property.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/Accessors.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/Data.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/Delegate.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/EqualsHashCode.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/FinalFieldsConstructor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/ToString.java

regenerated xtend code

---

releng/releng-target/xtext-lib.target.target

[eclipse/xtext#1682] update orbit to 2020-06

[eclipse/xtext#1682] update orbit to 2020-06

---

releng/pom.xml

Signed-off-by: Tamas Miklossy <miklossy@itemis.de>

[https://github.com/eclipse/xtext/issues/1732] Update to Tycho 1.7.0

---

org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext#1649] update to ASM 8.0

[eclipse/xtext#1649] update to ASM 8.0

---

org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext#1738] removed no longer needed icu dependency

---

gradle/versions.gradle
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtend.gwt/pom.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.gwt/pom.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml
releng/org.eclipse.xtext.xbase.lib/pom.xml
releng/p2/category.xml
releng/p2/pom.xml
releng/pom.xml
releng/releng-target/pom.xml

[releng] Update Xtext version to 2.23.0

---

releng/releng-target/xtext-lib.target.target

[eclipse/xtext#1781] update orbit to 2020-09

[eclipse/xtext#1781] update orbit to 2020-09

---

org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/declaration/MethodDeclaration.java

[#903] Added missing since tag, improved backwards compatibility

[#903] Added missing since tag, improved backwards compatibility

---

org.eclipse.xtend.lib.gwt.test/.project
org.eclipse.xtend.lib.gwt.test/build.gradle

Signed-off-by: Karsten Thoms <karsten.thoms@karakun.com>

[eclipse/xtext#1806] remove ModuleCoreNature

---

releng/releng-target/xtext-lib.target.target

[eclipse/xtext#1816] harmonize includeSource to true in preparation for tycho 2.0

[eclipse/xtext#1816] harmonize includeSource to true in preparation for tycho 2.0

---

gradle/versions.gradle
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtend.gwt/pom.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.gwt/pom.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml
releng/org.eclipse.xtext.xbase.lib/pom.xml
releng/p2/category.xml
releng/p2/pom.xml
releng/pom.xml
releng/releng-target/pom.xml

[releng] Update Xtext version to 2.24.0

---

releng/releng-target/xtext-lib.target.target

[eclipse/xtext#1828] update orbit to 2020-12

[eclipse/xtext#1828] update orbit to 2020-12

---

org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext#1851] Add junit.platform runner and suite-api to bom

---

org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext#1852] Update to ASM 9

[eclipse/xtext#1852] Update to ASM 9

---

org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext-core#1566] update to LSP4J 0.10.0

[eclipse/xtext-core#1566] update to LSP4J 0.10.0

---

gradle/versions.gradle
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtend.gwt/pom.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.gwt/pom.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml
releng/org.eclipse.xtext.xbase.lib/pom.xml
releng/p2/category.xml
releng/p2/pom.xml
releng/pom.xml
releng/releng-target/pom.xml

[releng] Update Xtext version to 2.25.0

---

releng/releng-target/xtext-lib.target.target

[eclipse/xtext#1882][2021-03] Update Orbit
DO NOT merge yet

[eclipse/xtext#1882][2021-03] Update Orbit

---

org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/CollectionExtensions.java

Signed-off-by: miklossy <miklossy@itemis.de>

Fixing typos in the javadoc comments.

---

org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext#1934] update to ASM 9.1

[eclipse/xtext#1934] update to ASM 9.1

---

org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext#1914] manage transitive deps explicitely in bom

[eclipse/xtext#1914] manage transitive deps explicitely in bom

---

gradle/versions.gradle
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtend.gwt/pom.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.gwt/pom.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml
releng/org.eclipse.xtext.xbase.lib/pom.xml
releng/p2/category.xml
releng/p2/pom.xml
releng/pom.xml
releng/releng-target/pom.xml

[releng] Update Xtext version to 2.26.0

---

releng/releng-target/xtext-lib.target.target

[eclipse/xtext#1944] update orbit to 2021-06

[eclipse/xtext#1944] update orbit to 2021-06

---

org.eclipse.xtext.dev-bom/build.gradle

use guice 5.0.1

---

1-gradle-build.sh

cleanup leftover when bom was defined in maven

cleanup leftover when bom was defined in maven

---

org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext#1978] update to asm 9.2

[eclipse/xtext#1978] update to asm 9.2

---

NOTICE.md
org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext#2020] update to classgraph 4.8.138

[eclipse/xtext#2020] update to classgraph 4.8.138

---

releng/releng-target/xtext-lib.target.target

[eclipse/xtext#2029] update to orbit 2022-03

[eclipse/xtext#2029] update to orbit 2022-03

---

org.eclipse.xtend.lib.gwt.test/build.gradle

bump gwt gradle plugin

---

org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/declaration/Modifier.java
org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/declaration/MutableElement.java
org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/declaration/ResolvedConstructor.java
org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/declaration/ResolvedExecutable.java
org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/declaration/ResolvedMethod.java
org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/declaration/ResolvedParameter.java
org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/declaration/ResolvedTypeParameter.java
org.eclipse.xtend.lib/deprecated/org/eclipse/xtend/lib/Data.xtend
org.eclipse.xtend.lib/deprecated/org/eclipse/xtend/lib/Property.xtend
org.eclipse.xtend.lib/src/org/eclipse/xtend/lib/annotations/Data.xtend
org.eclipse.xtend.lib/src/org/eclipse/xtend/lib/annotations/Delegate.xtend
org.eclipse.xtend.lib/src/org/eclipse/xtend/lib/annotations/EqualsHashCode.xtend
org.eclipse.xtend.lib/src/org/eclipse/xtend/lib/annotations/FinalFieldsConstructor.xtend
org.eclipse.xtend.lib/src/org/eclipse/xtend/lib/annotations/ToString.xtend
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/Data.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/DataProcessor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/Property.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/PropertyProcessor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/Data.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/DataProcessor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/Delegate.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/DelegateProcessor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/EqualsHashCode.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/EqualsHashCodeProcessor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/FinalFieldsConstructor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/FinalFieldsConstructorProcessor.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/ToString.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/ToStringConfiguration.java
org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/ToStringProcessor.java

added missing copyright headers

added missing copyright headers

---

gradle/versions.gradle
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtend.gwt/pom.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.gwt/pom.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml
releng/org.eclipse.xtext.xbase.lib/pom.xml
releng/p2/category.xml
releng/p2/pom.xml
releng/pom.xml
releng/releng-target/pom.xml

[releng] Update Xtext version to 2.27.0

---

org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext#2028] switch to reload4j

[eclipse/xtext#2028] switch to reload4j

---

NOTICE.md
org.eclipse.xtext.dev-bom/build.gradle
releng/releng-target/xtext-lib.target.target

[eclipse/xtext#2053] Update to ASM 9.3 [eclipse/xtext#2039] Update to Orbit 2022-06

[eclipse/xtext#2053] Update to ASM 9.3 [eclipse/xtext#2039] Update to Orbit 2022-06

---

org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext#2055]simplify dependencies to asm

[eclipse/xtext#2055]simplify dependencies to asm

---

org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext-core#1793]  update to lsp4j 0.13.0

[eclipse/xtext-core#1793]  update to lsp4j 0.13.0

---

org.eclipse.xtend.lib.gwt.test/.classpath

checkin .classpath as latest gradle and buildship versions generate it

checkin .classpath as latest gradle and buildship versions generate it

---

org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext-core#1902]update to lsp4j 0.14.0

[eclipse/xtext-core#1902]update to lsp4j 0.14.0

---

gradle/versions.gradle
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtend.gwt/pom.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.gwt/pom.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml
releng/org.eclipse.xtext.xbase.lib/pom.xml
releng/p2/category.xml
releng/p2/pom.xml
releng/pom.xml
releng/releng-target/pom.xml

[releng] Update Xtext version to 2.28.0

---

org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext-core#1904] update to lsp4j 0.15.0

[eclipse/xtext-core#1904] update to lsp4j 0.15.0

---

gradle/versions.gradle
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtend.gwt/pom.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.gwt/pom.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml
releng/org.eclipse.xtext.xbase.lib/pom.xml
releng/p2/category.xml
releng/p2/pom.xml
releng/pom.xml
releng/releng-target/pom.xml

[releng] Update Xtext version to 2.29.0

---

org.eclipse.xtext.dev-bom/build.gradle

bump classgraph to 4.8.149

---

gradle/eclipse-project-layout.gradle

fix a build problem when not calling xtend compiler

fix a build problem when not calling xtend compiler

---

NOTICE.md
releng/releng-target/xtext-lib.target.target

[eclipse/xtext#2089] Update to Orbit 2022-12 incl new classgraph & gson

[eclipse/xtext#2089] Update to Orbit 2022-12 incl new classgraph & gson

---

org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext-core#1943] update to lsp4j 0.16.0

[eclipse/xtext-core#1943] update to lsp4j 0.16.0

---

Jenkinsfile
build.gradle
gradle/java-compiler-settings.gradle
org.eclipse.xtend.lib.gwt.test/.classpath
org.eclipse.xtend.lib.gwt.test/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtend.lib.gwt/.classpath
org.eclipse.xtend.lib.gwt/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/.classpath
org.eclipse.xtend.lib.macro/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.tests/.classpath
org.eclipse.xtend.lib.tests/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtend.lib/.classpath
org.eclipse.xtend.lib/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.dev-bom/build.gradle
org.eclipse.xtext.xbase.lib.gwt/.classpath
org.eclipse.xtext.xbase.lib.gwt/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.tests/.classpath
org.eclipse.xtext.xbase.lib.tests/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.xbase.lib/.classpath
org.eclipse.xtext.xbase.lib/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/pom.xml

[eclipse/xtext#1982] support for java 17

[eclipse/xtext#1982] support for java 17

---

org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext-core#1986]update to lsp4j 0.17.0

[eclipse/xtext-core#1986]update to lsp4j 0.17.0

---

NOTICE.md
org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext#2104] update to asm 9.4

[eclipse/xtext#2104] update to asm 9.4

---

org.eclipse.xtend.lib.gwt.test/.project
org.eclipse.xtend.lib.gwt.test/build.gradle

switch to org.docstr.gwt (new name for org.wisepersist.gwt)

switch to org.docstr.gwt (new name for org.wisepersist.gwt)

---

org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext-core#1993] update to lsp4j 0.18.0

[eclipse/xtext-core#1993] update to lsp4j 0.18.0

---

org.eclipse.xtend.lib.gwt.test/.project

removed superflous wst nature

---

releng/releng-target/xtext-lib.target.target

[eclipse/xtext#2112] Fix Orbit signing problem

[eclipse/xtext#2112] Fix Orbit signing problem

---

releng/releng-target/xtext-lib.target.target

[eclipse/xtext#2112] switch back to orbit 2022-12

[eclipse/xtext#2112] switch back to orbit 2022-12

---

org.eclipse.xtext.dev-bom/build.gradle

[eclipse/xtext-core#2004] Update to lsp4j 0.19.0

[eclipse/xtext-core#2004] Update to lsp4j 0.19.0

---

gradle/versions.gradle
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtend.gwt/pom.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.gwt/pom.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml
releng/org.eclipse.xtext.xbase.lib/pom.xml
releng/p2/category.xml
releng/p2/pom.xml
releng/pom.xml
releng/releng-target/pom.xml

[releng] Update Xtext version to 2.30.0

---

org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/util/ReflectExtensions.java

fix java 9+ deprecations

---

org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtend.gwt/pom.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.gwt/pom.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml
releng/org.eclipse.xtext.xbase.lib/pom.xml
releng/p2/category.xml
releng/p2/pom.xml
releng/pom.xml
releng/releng-target/pom.xml

[releng] Update Xtext version to 2.28.1

---

org.eclipse.xtend.lib.gwt.test/build.gradle

bump gwt plugin

---

org.eclipse.xtext.dev-bom/build.gradle
releng/releng-target/xtext-lib.target.target

[eclipse/xtext#2118] update to orbit 2023-03

[eclipse/xtext#2118] update to orbit 2023-03

---

org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/util/ToStringBuilder.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/util/ToStringContext.java

fix unused imports

---

org.eclipse.xtext.xbase.lib.gwt/src-super/org/eclipse/xtext/xbase/lib/super/org/eclipse/xtext/xbase/lib/util/ToStringContext.java
org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/FunctionCompositionTest.java
org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/MapExtensionsTest.java

more warnings cleanup

---

gradle/versions.gradle
org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
org.eclipse.xtend.lib/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
releng/org.eclipse.xtend.gwt/feature.xml
releng/org.eclipse.xtend.gwt/pom.xml
releng/org.eclipse.xtext.gwt/feature.xml
releng/org.eclipse.xtext.gwt/pom.xml
releng/org.eclipse.xtext.xbase.lib/feature.xml
releng/org.eclipse.xtext.xbase.lib/pom.xml
releng/p2/category.xml
releng/p2/pom.xml
releng/pom.xml
releng/releng-target/pom.xml

[releng] Update Xtext version to 2.31.0

---

org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/util/ReflectExtensionsTest.java
org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/util/ReflectExtensions.java

[#513] fix ReflectExtensions.invoke for static methods

[#513] fix ReflectExtensions.invoke for static methods
