org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/IterableExtensionsTest.java, org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/IteratorExtensionsTest.java, org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IterableExtensions.java, org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IteratorExtensions.java
Implemented IterableExtensions/IteratorExtensions.reject
https://bugs.eclipse.org/bugs/show_bug.cgi?id=382213
=> Implemented IterableExtensions.reject

org.eclipse.xtend.lib/src/org/eclipse/xtend/lib/annotations/Delegate.xtend, org.eclipse.xtend.lib/src/org/eclipse/xtend/lib/annotations/FinalFieldsConstructor.xtend, org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/DelegateProcessor.java, org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/FinalFieldsConstructorProcessor.java, org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/util/ToStringBuilder.xtend, org.eclipse.xtext.xbase.lib/xtend-gen/org/eclipse/xtext/xbase/lib/util/ToStringBuilder.java, org.eclipse.xtext.xbase.lib/xtend-gen/org/eclipse/xtext/xbase/lib/util/ToStringContext.java
For comparison with null the triple (not) equal operator should be used.
Resolved compiler warnings
=> [eclipse/xtext#1089] Replace (not)equal operators by triple (not)equals

gradle.properties
Avoids a circular dependency when running the build from the umbrella's composite
=> [eclipse/xtext-umbrella#14] set skipXtendCompiler property

org.eclipse.xtend.lib.gwt.test/build.gradle
fixed broken classpath (gwt plugin is now on jcenter)
=> fixed broken classpath

org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IteratorExtensions.java
Be more explicit in JavaDoc of IteratorExtensions.toIterable. Fixes #46
=> Be more explicit in JavaDoc of IteratorExtensions.toIterable. Fixes #46

org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
Increased guava version to include version 21.
https://github.com/eclipse/xtext-lib/issues/30
=> Increased guava version to include version 21.

org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/CollectionLiterals.java
* When `newHashMap` or `newLinkedHashMap` is used without parameters, I would expect the same result that I get with `new HashMap` or `new LinkedHashMap`: maps initialized with the default capacity (16). Previously they were initialized with a capacity of 1, which means that rehashing was necessary even if you put just a few elements into them.
* The `LinkedHashMap` constructor is now called with the capacity value, which is 4/3 &times; the initial size due to the load factor. Previously the initial size was used, which means that rehashing was necessary for the initial content.
=> Improved performance of newHashMap etc.

org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF, org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF, org.eclipse.xtend.lib/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
Signed-off-by: Florian Stolte <fstolte@itemis.de>
=> [eclipse/xtext#1152] Java 9 - Added Automatic-Module-Name header

org.eclipse.xtend.lib.tests/src/org/eclipse/xtend/lib/annotations/DataTest.xtend, org.eclipse.xtend.lib.tests/xtend-gen/org/eclipse/xtend/lib/annotations/DataTest.java, org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/StringConcatenationTest.java
- StringConcatenationTest has hard-coded unix-style line endings, therefore the StringConcatenation must be set to unix-style line endings as well (instead of system-style)
- org.eclipse.xtend.lib.annotations.DataTest failed because ToStringBuilder always used unix-style line endings while test data used system-style line endings. Changed ToStringBuilder to use system-style line endings. I changed the implementation instead of the test since it seems logical to me that the ToStringBuilder should use system-style line endings.
Signed-off-by: Florian Stolte <fstolte@itemis.de>
=> Fixed some tests that were failing on windows due to line endings

org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/IterableExtensionsTest.java, org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IterableExtensions.java
This API exists for filter, but not for reject
=> Added reject with only a Class argument

org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF, org.eclipse.xtend.lib/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
[eclipse/xtext#1270] use JavaSE-1.8 as BREE
=> [eclipse/xtext#1270] use JavaSE-1.8 as BREE

org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/MapExtensions.java
The mapValues functions within MapExtensions could be annoted as pure
function because it has no border effect on its parameters.
It could also be inlined.
Signed-off-by: Stéphane Galland <galland@arakhne.org>
=> Make pure and inlinable the MapExtensions.mapValues function.

Jenkinsfile, gradle/bootstrap-setup.gradle
Build steps defined in Jenkinsfile pass the built-in environment
variable 'JENKINS_URL' to the Gradle/Maven executions. This is evaluated
in the build scripts for upstream repository URLs. On Xtext JIPP this
will use upstream repos from JIPP. In local builds outside of Jenkins
the property defaults to Typefox CI like before.
=> [eclipse/xtext#1224] Detect local Jenkins environment

org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/EqualsHashCodeProcessor.java, org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/FinalFieldsConstructorProcessor.java
Order of static & final modifiers changed
(eclipse/xtext-xtend#554)
=> [eclipse/xtext#1272] Compile with Xtend 2.15

org.eclipse.xtend.lib.gwt.test/build.gradle
[eclipse/xtext#1280] use newer version of gwt gradle plugin
=> [eclipse/xtext#1280] use newer version of gwt gradle plugin

org.eclipse.xtend.lib.gwt/build.gradle, org.eclipse.xtext.xbase.lib.gwt/build.gradle
[eclipse/xtext-lib#131] announce deprecation of xbase and xtend gwt libs
=> [eclipse/xtext-lib#131] announce deprecation of xbase and xtend gwt libs

2-gradle-build.sh, build.gradle, gradle/developers.gradle, gradle/maven-deployment.gradle, gradle/versions.gradle, releng/org.eclipse.xtext.dev-bom/pom.xml
- use maven-publish plugin instead of deprecated maven plugin
- remove Spring dependency-management-plugin
- disable javadoc publishing for test projects (they don't produce a
javadoc jar)
=> [eclipse/xtext#1249] Use Gradle native BOM management

releng/org.eclipse.xtext.dev-bom/pom.xml
[eclipse/xtext#1182] added support for java 11 as target
=> [eclipse/xtext#1182] added support for java 11 as target

releng/org.eclipse.xtext.dev-bom/pom.xml
[eclipse/xtext#1283] update to mwe 2.10 final
do not merge before MWE 2.10 is released
=> [eclipse/xtext#1283] update to mwe 2.10 final

README.md, gradle/bootstrap-setup.gradle
Use https://ci.eclipse.org/xtext as default Jenkins URL
=> [eclipse/xtext#1424] Change default Jenkins

org.eclipse.xtend.lib/src/org/eclipse/xtend/lib/annotations/Delegate.xtend, org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/DelegateProcessor.java
[eclipse/xtext-core#1137] Filter static methods in Delegate active annotation
=> [eclipse/xtext-core#1137] Filter static methods in Delegate active annotation

org.eclipse.xtend.lib.gwt.test/.classpath, org.eclipse.xtend.lib.gwt.test/.project, org.eclipse.xtend.lib.gwt.test/build.gradle
Replaced GWT Gradle plugin https://github.com/jiakuan/gwt-gradle-plugin with https://github.com/esoco/gwt-gradle-plugin
The jiakuan-plugin has a note for Gradle 5.2+ but no example for actual usage.
The esoco-plugin seems to be maintained and has an actual documentation for usage.
An alternative could be https://github.com/ascendtech/gwt-gradle but this project is just one year old.
An secound alternative could be https://github.com/big-guy/gwt-gradle-plugin. There are few commits for mantaining new gradle versions, but no up to date releases for this.
=> [#131] eliminated compile errors in GWT tests

CBI.Jenkinsfile, Jenkinsfile
Replaces #192, since changes to Jenkinsfile by contributors are untrusted and not executed in PR builds. Adopted changes from #192.
- [eclipse/xtext#1431] Add resource limits to fix OOM failures
- [eclipse/xtext#1463] Configure job timeouts
- [eclipse/xtext#1465] Use declarative JUnit step
- Add JIRO as known environment qualifier for build notification message
Also-by: Nico Prediger <mail@nicoprediger.de>
=> [releng] Fix minor issues with JIRO

org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.dev-bom/pom.xml
Fixes eclipse/xtext#1398 and eclipse/xtext-lib#111
=> update to guava 27.1

2-gradle-build.sh, CBI.Jenkinsfile, org.eclipse.xtend.lib.gwt.test/build.gradle
- Disable Gradle daemon, since a new container for each build is
spawned and the daemon can't be reused anyway.
- Remove CPU resource constraint, since default is sufficient.
- Remove memory options for GWT compile. Works also without and
potentially causes problems in memory limited containers, esp. when
minHeapSize can't be assured.
- Remove cleanup of Maven repo: Not necessary when running in a
container. The Maven repo is always empty at beginning.
- Remove memory settings for GWT compile task: Potentially causes
problems in memory limited container
=> [eclipse/xtext#1431] Enhancing container support

releng/releng-target/xtext-lib.target.target
[eclipse/xtext#1279] use orbit simrel alias directly
=> [eclipse/xtext#1279] use orbit simrel alias directly

releng/org.eclipse.xtext.dev-bom/pom.xml
[eclipse/xtext-core#1082] update to lsp4j 0.8.0
=> [eclipse/xtext-core#1082] update to lsp4j 0.8.0

org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsBooleanTest.xtend, org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsByteTest.xtend, org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsCharTest.xtend, org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsDoubleTest.xtend, org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsFloatTest.xtend, org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsIntTest.xtend, org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsLongTest.xtend, org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsObjectTest.xtend, org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsShortTest.xtend, org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/IterableExtensionsTest.java, org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/IteratorExtensionsTest.java, org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsBooleanTest.java, org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsByteTest.java, org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsCharTest.java, org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsDoubleTest.java, org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsFloatTest.java, org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsIntTest.java, org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsLongTest.java, org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsObjectTest.java, org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsShortTest.java, org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/ArrayExtensions.java, org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IterableExtensions.java, org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IteratorExtensions.java
added a contains method to arrayExtensions for Object and all scalar
datatypes as well as for Iterables and Iterators. It uses
java.lang.Objects.equals(...) where applicable.
Furthermore I added tests for the different ArrayExtension methods
Signed-off-by: Mathias Rieder <mathias.rieder@gmail.com>
=> [eclipse/xtext-xtend#877] added 'contains' to array/iterable/iterator

releng/org.eclipse.xtext.dev-bom/pom.xml
As noted here https://www.eclipse.org/forums/index.php/t/1101550/ `mwe.core` is not dragged in automatically anymore in Maven builds, and must be explicitly added. If one relies on the xtext-dev-bom it would be nice to add mwe.core to the BOM
Signed-off-by: Lorenzo Bettini <lorenzo.bettini@gmail.com>
=> Add mwe.core to xtext-dev-bom

org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/ArrayExtensions.java, org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IteratorExtensions.java
- > Task :org.eclipse.xtext.xbase.lib:javadoc
C:\Users\miklossy\git\xtext-lib\org.eclipse.xtext.xbase.lib\src\org\eclipse\xtext\xbase\lib\ArrayExtensions.java:562:
warning - @param argument "o" is not a parameter name.
C:\Users\miklossy\git\xtext-lib\org.eclipse.xtext.xbase.lib\src\org\eclipse\xtext\xbase\lib\IteratorExtensions.java:1082:
warning - @param argument "iterable" is not a parameter name.
2 warnings
Signed-off-by: Tamas Miklossy <miklossy@itemis.de>
=> Fix javadoc warnings in ArrayExtensions and IteratorExtensions classes.

org.eclipse.xtext.dev-bom/build.gradle
[eclipse/xtext-core#1244] update to LSP4J 0.9.0 release
=> [eclipse/xtext-core#1244] update to LSP4J 0.9.0 release

org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/declaration/MethodDeclaration.java, org.eclipse.xtend.lib/src/org/eclipse/xtend/lib/annotations/Accessors.xtend, org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/Accessors.java, org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/AccessorsDeprecationPolicy.java, org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/AccessorsProcessor.java
The `@Accessors` can now delegate annotations to the getters.
The annotation detects deprecated fields and generates `@Deprecated` when required. It is an error to set any of the deprecation fields on the annotation when the field is already deprecated (checked by the Java compiler, not by the annotation processor).
The setter can be set to return `this`.
The annotation can delegate warning types to suppress.
Classes may declare a "custom getter" by annotating one instance method with `@CustomGetter`. Such methods have to take no arguments and cannot be static, and cannot return void. (The void method validation is done by the Java compiler, not by the annotation processor). When a class uses a custom getter, an additional method is generated for annotated fields of that type: a "raw" …
=> [eclipse/xtext-xtend#903] Overhaul Accessors Annotation

org.eclipse.xtend.lib.gwt.test/build.gradle
bump gwt gradle plugin to avoid gradle 8.0 deprecation warnings
=> bump gwt gradle plugin to avoid gradle 8.0 deprecation warnings

org.eclipse.xtend.lib.gwt.test/src/org/eclipse/xtend/lib/test/Test.gwt.xml
use https in dtd link to avoid validation error in eclipse
=> use https in dtd link to avoid validation error in eclipse

org.eclipse.xtext.dev-bom/build.gradle
[eclipse/xtext-core#2019] update to lsp4j 0.20.0
=> [eclipse/xtext-core#2019] update to lsp4j 0.20.0
